### ISSUE TITLE
Support async/callables for choices argument

### ISSUE THREAD

**Issue by gresnick** [tmbo/questionary#112]
Currently, the `choices` argument must be a `Sequence`. The generation cost of this sequence can be high (e.g. IO bound, such an API call) which are called upon creation of the prompt and can create a latency to the start of script. In some cases, the prompt may be conditional and may never even be displayed. 

Consider this example:

```
def prompt_questions(difficult_decision):
    return questionary.unsafe_prompt(
        [
            {
                'type': 'confirm',
                'name': 'confirm',
                'message': f'Confirm decision {difficult_decision}',
                'when': lambda _: difficult_decision is not None,
                'default': False,
            },
            {
                'type': 'checkbox',
                'name': 'other_difficult_decisions',
                'message': 'Make your choices',
                'when': lambda x: not x.get('confirm'),
                'validate': lambda value: True if len(value) > 0 else 'You must select at least one decision',
                'choices': long_api_call_to_get_all_life_decisions(difficult_decision),
            },
        ]
    )
```

In this example, if the `confirm` stage returns `True`, `other_difficult_decisions` is never prompted, however, `long_api_call_to_get_all_life_decisions` was already called, creating a delay before `confirm` was prompted.

It would be great if instead a `callable` could be passed along and called at prompt time, in essence:

```
def prompt_questions(difficult_decision):
    return questionary.unsafe_prompt(
        [
            {
                ...
                'choices': functools.partial(long_api_call_to_get_all_life_decisions, difficult_decision),
            },
        ]
    )
```

With that said, first prize would be to support an asyncronous call as a choice, which is only yielded at prompt time.

**Comment by HolgerDoerner** [comment]
@gresnick what do You exactly mean with "first prompt"? In my tests, only the question with the long running choices-callable takes time to load, all other before work just fine. 

But to answer Your question "Why should the entire prompt flow wait for the response to this request" directly: The prompt for a specific question has to wait because without the choices, there is nothing to do further for him. If gathering Your choices is based on information which is only available at this point, like an answer from the question before, then this is nothing async would solve. Async only solves a problem where data isn't needed **RIGHT NOW**. For example, if You are able to fetch data **BEFORE** it is needed and let a function run async to fetch it while other stuff is going on. But this is the responsibility of the developer, not the library.

You could work async INSIDE of Your choices-callable and yielding the results. Basically turning it into an Generator, and adding the choices as they arrive. Not tested by me, but it should work.

For anything else, an `unsafe_prompt_async` with complete asynchronous control-flow has to be implemented. Just calling `choices(answers)` async, or even just `await` it, doesn't solve the problem You described, I'm sorry.
