### ISSUE TITLE
Default select value not working with values from interable

### ISSUE THREAD

**Issue by mosfetish** [tmbo/questionary#124]
For dict:

```
codes = {
    '123':  'Helper text for this code',
    '456':  'Helper text for this code,
    '789':  'Helper text for this code'
}
```

This:

```
x = questionary.select(
    "Select a code",
    default='789',
    choices=[
        questionary.Choice(title=f"{code} {text}", value=code)
        for code, text in codes.items()
    ],
).ask()
```

Produces error:

"ValueError: Invalid `default` value passed. The value (`789`) does not exist in the set of choices. Please make sure the default value is one of the available choices."

Default choice works when code is reduced to:

```
x = questionary.select(
    "Select a code",
    default='789',
    choices=['123', '456', '789'],
).ask()
```

**Comment by kiancross** [comment]
The `default` value needs to be the same type as used in the `choices` iterable. 

In your second example, `choices` is a list of strings and so `default='789'` is valid. However, in your first example, you are mixing `Choice` instances and strings. Instead, you can do something like this:

```python3
import questionary

codes = {
    "123": "Helper text for this code",
    "456": "Helper text for this code",
    "789": "Helper text for this code",
}

choices = {
    code: questionary.Choice(title=f"{code} {text}", value=code)
    for code, text in codes.items()
}

x = questionary.select(
    "Select a code", default=choices["789"], choices=list(choices.values())
).ask()

print(x)
```

**Comment by mosfetish** [comment]
Thanks for the quick reply. I'm not sure I'd have worked that out anytime soon since I got a valueError and not a typeError.

**Comment by kiancross** [comment]
In the general case, the `choices` iterable can be a mixed list, for example, containing strings and `Choice` instances.

So I think a `ValueError` is correct, as we are checking if the given `default` value exists in the `choices` array (rather than checking if the type is the same).

**Comment by WilliamStam** [comment]
dealing with this again so looked if anything has changed. think the issue is that this isnt "intuitive". (related to https://github.com/tmbo/questionary/issues/57) 

i think "default" should first check if the object is a Choice instance (to keep backwards compatibility) if its not then if the value is in the list of choices select that choice if not then throw the error. 

not enjoying having to keep a list of the choices and then finding the right choice for default just to keep this working. 

will look if i can do a PR maybe
