### ISSUE TITLE
Support choices with None value

### ISSUE THREAD

**Issue by Yajo** [tmbo/questionary#126]
Unexpected behavior:

```python
>>> from questionary.prompts.common import Choice
>>> c = Choice(title="name", value=None)
>>> assert c.value is None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

Expected behavior: pass that assertion

**Comment by kiancross** [comment]
I think this is the expected behaviour - when `value` is not set, it takes the value of `title`.

https://github.com/tmbo/questionary/blob/3556d33238675808b19f27b8ab0584ed3eaa02a8/questionary/prompts/common.py#L82-L83

The docs could probably be clearer about this. Is there is a use case for changing this behaviour?

**Comment by Yajo** [comment]
Well... it means a regression in copier from a previous version that wasn't using questionary, but I'm thinking it's probably an absurd use case anyway. 

Maybe some better docs would be enough.

**Comment by kiancross** [comment]
I'll add this to the docs in a couple of weeks when I go through some of the other issues :)
