### ISSUE TITLE
Want to select a element from database using questionary. Returns right value but cannot delete it using my delete function

### ISSUE THREAD

**Issue by kmeans27** [tmbo/questionary#247]
### Question

Hello,

I coded a select option so the user can simply use his keyboard to select a habit to delete. The select method returns the exact name but I can somehow not delete any rows in my Sqlite3 database even though the remove method is working?
here are some screenshot if this helps: [https://imgur.com/a/VrfEb48](url)

```
def get_habits():
    cursor.execute("SELECT name FROM habits")
    habit_names = cursor.fetchall()
    return [i[0] for i in set(habit_names)]
```

```
def select_habit():
    habits = get_habits()
    return questionary.select("Select a habit:",
                              choices=sorted(habits)).ask().lower()
```

```
def remove_habit(habit_name):
    with conn:
        cursor.execute(f"DELETE FROM habits WHERE name == '{habit_name}'")
```
```
    if navigation == "Delete existing habits":
        habit_to_delete = data.select_habit()
        print(habit_to_delete)
        choice = questionary.confirm("Are you sure?").ask()
        if choice == "Yes":
            data.remove_habit(habit_to_delete)

```

### What have you already tried?

I have tried everything. I need another point of view. Even if i took the past code from a github release where everything worked perfectly, it still doesn't work.

here is my repo if this helps: [https://github.com/kmeans27/habit_tracker](url)

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
This doesn't sound like a problem with Questionary specifically, but a general bug in your code. I'll close this issue for now, but if you disagree and think that there is indeed a problem with Questionary, please post back. Some general pointers to help you debug your code:

 - Check the return value of your `cursor.execute` statement - I suspect you will find there is an error here.
 - Using formatted strings to add `habit_name` to the SQL statement is a bad idea (and might even be the cause of your issue). It leaves you vulnerable to [SQL injections](https://www.w3schools.com/sql/sql_injection.asp).
 - Instead, you should use prepared statements, where you put a `?` in place of the variable, and pass the variable as a separate parameter.

**Comment by kmeans27** [comment]
Hi @kiancross , thank you for you reply and sorry to bother you again.
I still haven't solved the issue.  I read through your comment multiple times.

As I didn't know the error I am now trying to implement some unittests. 

Could you please tell me, **how I can unittest the return from the select_habit() function?** So that I can finally solve this issue and move on.

**Comment by kiancross** [comment]
> Could you please tell me, how I can unittest the return from the select_habit() function? So that I can finally solve this issue and move on.

You can take a look at [how we have implemented unit tests](https://github.com/tmbo/questionary/tree/master/tests) to get an idea about how you may wish to do this.

> As I didn't know the error I am now trying to implement some unittests.

Unit tests are great for catching [regressions](https://en.wikipedia.org/wiki/Software_regression). However, they're probably not going to help you get to the bottom of this issue.

I've taken a look at your code, and I'll give you some clues.

1. You have a [print statement](https://github.com/kmeans27/habit_tracker/blob/0dfef3dee8321248ef8a1519f97c4161242abbbb/main.py#L45) in `main.py` which says `print(habit_to_delete)`. When you run your code do you see this output? If so, you know your code has at least reached this point! Otherwise, the problem must be earlier on, and you need to put more print statements _before_ this line. If you see the message, continue onwards to the next step.
2. On [line 47](https://github.com/kmeans27/habit_tracker/blob/0dfef3dee8321248ef8a1519f97c4161242abbbb/main.py#L47) you have an if statement. Try putting a print statement after this, e.g.
```python3
        if choice == "Yes":
            print("Deleting habit")
            data.remove_habit(habit_to_delete)
```
3. When you run your code, do you see the message `Deleting habit`? If not, the problem must be somewhere between lines 45 and 47. What is the value of `choice`? Are you sure that it is equal to the string `Yes`? Or is it actually something else?! Try printing out `choice` to see what it actually is...

**Comment by kmeans27** [comment]
Omg you just made my day kind sir!

All i did was moving the "data.remove_habit(habit_to_delete)" just above t he if statement. The code executed fine! everything working perfectly now. Somehow the under the if statement was not executed.

`    if navigation == "Delete existing habits":
        habit_to_delete = data.select_habit()
        print(habit_to_delete)
        **data.remove_habit(habit_to_delete)**
        # print(data.get_all_data())
        choice = questionary.confirm("Are you sure?").ask()
        if choice == "Yes":
            print("Deleting habit")
            data.remove_habit(habit_to_delete)
`

Thank you again, have a nice day!

**Comment by kiancross** [comment]
The reason the code inside the if statement is not executing is because the if statement is not true. `choice` is _not_ equal to `"Yes"`. The correct if statement if `if choice:`, because `choice` is a boolean.
